CREATE TABLE FEATURE (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE MATERIAL_TYPE (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE SEED_VARIETY (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE SEED_STARTER (
  ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
  MATERIAL_TYPE_ID BIGINT NOT NULL,
  DATE_PLANTED     DATE   NOT NULL,
  COVERED          BOOLEAN            DEFAULT FALSE,

  FOREIGN KEY (MATERIAL_TYPE_ID) REFERENCES MATERIAL_TYPE (ID)
);

CREATE TABLE SEED_STARTER_FEATURE (
  SEED_STARTER_ID BIGINT NOT NULL,
  FEATURE_ID      BIGINT NOT NULL,

  FOREIGN KEY (SEED_STARTER_ID) REFERENCES SEED_STARTER (ID),
  FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE (ID)
);

CREATE TABLE ROW (
  ID              BIGINT PRIMARY KEY NOT NULL,
  SEED_STARTER_ID BIGINT             NOT NULL,
  SEED_VARIETY_ID BIGINT             NOT NULL,
  SEEDS_PER_CELL  INT                NOT NULL,

  FOREIGN KEY (SEED_STARTER_ID) REFERENCES SEED_STARTER (ID),
  FOREIGN KEY (SEED_VARIETY_ID) REFERENCES SEED_VARIETY (ID)
);
