INSERT INTO FEATURE (ID, NAME)
VALUES (1, 'Specific Substrate'), (2, 'Fertilizer'), (3, 'Ph Corrector');

INSERT INTO SEED_VARIETY (ID, NAME)
VALUES (1, 'Thymus Caespititius'), (2, 'Thymus Camphoratus'), (3, 'Thymus Capitellatus');

INSERT INTO MATERIAL_TYPE (ID, NAME)
VALUES (1, 'Plastic'), (2, 'Wood'), (3, 'Iron');

INSERT INTO SEED_STARTER (ID, MATERIAL_TYPE_ID, DATE_PLANTED, COVERED)
VALUES (1, 1, '2017-04-01', TRUE);

INSERT INTO SEED_STARTER (ID, MATERIAL_TYPE_ID, DATE_PLANTED, COVERED)
VALUES (2, 2, '2017-04-02', FALSE);

INSERT INTO SEED_STARTER (ID, MATERIAL_TYPE_ID, DATE_PLANTED, COVERED)
VALUES (3, 2, '2017-04-05', TRUE);


INSERT INTO SEED_STARTER_FEATURE (SEED_STARTER_ID, FEATURE_ID)
VALUES (1, 1);

INSERT INTO SEED_STARTER_FEATURE (SEED_STARTER_ID, FEATURE_ID)
VALUES (1, 2);

INSERT INTO SEED_STARTER_FEATURE (SEED_STARTER_ID, FEATURE_ID)
VALUES (2, 2);


INSERT INTO ROW (SEED_STARTER_ID, SEED_VARIETY_ID, SEEDS_PER_CELL)
VALUES (1, 1, 3);

INSERT INTO ROW (SEED_STARTER_ID, SEED_VARIETY_ID, SEEDS_PER_CELL)
VALUES (1, 2, 2);

INSERT INTO ROW (SEED_STARTER_ID, SEED_VARIETY_ID, SEEDS_PER_CELL)
VALUES (2, 2, 5);
